### ISSUE TITLE
Fix internal (custom) IDs with Integer type

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/graphql-server-model-codegen#223]
# Interal (custom) IDs currently only work with String types

The reason for this is, that GraphQL internally uses Strings for its `ID` type. Now, when our Zendro validation framework kicks in and validates a custom Identifier of type Int, it correctly generates a validation error.

## Solution

Implement a new function which we could call 
`preValidationCast`.
In this function we could do the conversion of `internalId`, or even all ID, values to 
the type registered in the data model definition. If no ID is registered, we use 
Integer by default.

## Integration test

Add an integration test, that tests Zendro behaviour with `internalId` and Int type.

**Comment by qwerdenkerXD** [comment]
@asishallab Doesn't do `postReadCast` what we want?
I would edit it a little bit, because JSON.parse won't work for Date, Time and DateTime and is a little bit ambitious anyway.

Concerning the integration test: The tests don't work since I'm working on Zendro (not only because Zendro wasn't working). They should be maintained by someone before I write a new test.

**Comment by asishallab** [comment]
@qwerdenkerXD thank you for your remarks!

I would not want to solve the issue using the function `postReadCast` because its purpose is a different one, as the name suggests. If both functions, the existing `postReadCast` and the planned one, do the same thing, we can do one of the following:
- use `postReadCast` and rename it to e.g. `castForValidation` if that'd be appropriate in your opinion
- use both the existing and planned functions and, where they share functionality call a third function `castIdentifierToCorrectType` that casts the ID values to the appropriate type

Please let me know, what you think!

**Comment by qwerdenkerXD** [comment]
@asishallab I think that a third function would make sense, maybe `castAttributeToCorrectType`.
That should be responsible for the type cast. With it, `postReadCast` could cast every attribute into its respective type. After that, the `castIdentifierToCorrectType` could be called for the ID conversion, which is also called before the validation happens in the create and update function. This function would use the `castAttributeToCorrectType` as well.

**Comment by coeit** [comment]
I guess you could do that in the `add<model>` and `update<modle>` resolvers where we already sanitize associationInputs via the `sanitizeAssociationArguments` helper. Just add another helper that further sanitizes the input by casting the correct types. That also removes the problem of doing it on model level for each storageType differently. Just do it once in the resolver. e.g

```node
addCat: async function(input, context) {
    let authorization = await checkAuthorization(context, 'Cat', 'create');
    if (authorization === true) {
        let inputSanitized = helper.sanitizeAssociationArguments(input, [Object.keys(associationArgsDef)]);
        // TODO: add helper function to further sanitize the input arguments
        await helper.checkAuthorizationOnAssocArgs(inputSanitized, context, associationArgsDef, ['read', 'create'], models);
        await helper.checkAndAdjustRecordLimitForCreateUpdate(inputSanitized, context, associationArgsDef);
        if (!input.skipAssociationsExistenceChecks) {
            await helper.validateAssociationArgsExistence(inputSanitized, context, associationArgsDef);
        }
        let token = context.request ?
            context.request.headers ?
            context.request.headers.authorization :
            undefined :
            undefined;
        let createdCat = await cat.addOne(inputSanitized, context.benignErrors, token);
        await createdCat.handleAssociations(inputSanitized, context.benignErrors, token);
        return createdCat;
    } else {
        throw new Error("You don't have authorization to perform this action");
    }
}
```

The `preWriteCast` and `postReadCast` functions are sql storage specific. They are used to cast array types into JSON, which are then written into storage and vice versa. Casting the input to the expected types wouldn't be storage specific i guess.

**Comment by qwerdenkerXD** [comment]
Well, if @asishallab is fine with doing it inside the resolvers, I have already satisfied some changes [here](https://www.github.com/Zendro-dev/graphql-server/pull/106) and [here](https://www.github.com/Zendro-dev/graphql-server-model-codegen/pull/222), because I'm also not excited to edit all the model files separately with accidentally creating new Errors. In the end I wasn't sure if it hurts the separation of concern.

@coeit Concerning the other methods: Currently, there is no validation implemented for deleting records.
Good point that `postReadCast` is sql-specific, so the read methods will also need the type cast
